### ISSUE TITLE
How to create class constants?

### ISSUE THREAD

**Issue by joehoyle** [davidcole1340/ext-php-rs#122]
When using the `#[php_class]` macro on a `struct`, I'm trying to also set a PHP class constant, but I don't see any support. Am I missing something here on how to register class constants (either via macros or procedurally)

**Comment by TorstenDittmann** [comment]
You should be able to do this

```rust
#[php_class]
pub struct Human {
    name: String,
    age: i32,
}

#[php_impl]
impl Human {
    const MAX_AGE: i32 = 100;

    pub fn __construct(name: String, age: i32) -> Self {
        Self { name, age }
    }

    pub fn get_max_age() -> i32 {
        Self::MAX_AGE
    }
}
```

```php
$me = new Human('David', 20);

var_dump(Human::get_max_age()); // int(100)
var_dump(Human::MAX_AGE); // int(100)
```

**Comment by joehoyle** [comment]
@TorstenDittmann ahh nice find! So, specifically in my case I actually need to set the constant at runtime, so I think I'll need to set the constant on the ZendRegisteredClass (or similar) at runtime to set it to a computed value. I should be able to look up the `impl` macro and see how ext-php-rs is setting constants on that class and do that proceduraly instead

**Comment by davidcole1340** [comment]
@joehoyle I have added the ability to pass a 'modifier' function to a PHP class. It will be called before the class entry is built with PHP so you can add any extra functions or constants there.

The function must take one parameter: an instance of `ext_php_rs::builders::ClassBuilder` and return the same object in a `Result` (the error can be anything, the result is unwrapped).

This is currently on the `class_modifier` branch so let me know if you get a chance to try it out.

Example:

```rs
use ext_php_rs::{builders::ClassBuilder, error::Result as EResult, prelude::*};

#[php_class(modifier = "human_modifier")]
pub struct Human {
    name: String,
    age: i32,
}

pub fn human_modifier(class: ClassBuilder) -> EResult<ClassBuilder> {
    class.constant("MY_CONSTANT_NAME", 5)
}

#[php_module]
pub fn get_module(module: ModuleBuilder) -> ModuleBuilder {
    module
}
```

You should now be able to call a function at runtime in place of `5`.
