### ISSUE TITLE
Problem with `FromZval<'_>` is not implemented

### ISSUE THREAD

**Issue by taophp** [davidcole1340/ext-php-rs#160]
Hello,

I'm quite new to Rust, so forgive me if I ask a naive question.
I've written an experimental library, named mogul, that I try to bind to PHP. And I meet a problem I don't understand.
When I try to compile, Cargo tells me :
```bash
the trait `FromZval<'_>` is not implemented for `MogulHl`
```
Here is the binding code (actually, my last try):
``` rust
#![cfg_attr(windows, feature(abi_vectorcall))]
use ext_php_rs::prelude::*;
use mogul::*;

#[php_class]
pub struct MogulHl {
    mogul: MogulHandler,
}

#[php_impl]
impl MogulHl {
    pub fn allow_merge(original: MogulHl, challenger: MogulHl) -> PhpResult<()> {
        match mogul_allow_update(&original.mogul, &challenger.mogul) {
            Ok(()) => Ok(()),
            Err(MogulError::ChallengerOlderThanOriginal) => {
                Err(PhpException::default("Challenger older than the original".into()))
            } ,
            Err(MogulError::Conflict) => {
                Err(PhpException::default("Conflict between the two versions".into()))
            },
            Err(MogulError::IdenticalVersions) => {
                PhpResult::Err(PhpException::default("Identical versions".into()))
            },
            Err(MogulError::NotVersionsOfTheSameObject) => {
                PhpResult::Err(PhpException::default("Versions of different objects".into()))
            },
        }
    }
}

#[php_module]
pub fn get_module(module: ModuleBuilder) -> ModuleBuilder {
    module
}
```
Can anyone help me with this ?

**Comment by ptondereau** [comment]
Hey @taophp 
Do you have a minimal repository that reproduce your error?

Your error tells you that Rust part of your extension can't recreate your struct `MogulHl` from a pure PHP type (string/array/object...) but it can be another error underlying.

Please try:
```rust
    pub fn allow_merge(original: &MogulHl, challenger: &MogulHl) -> PhpResult<()> {
 ```
 
 Suggestion:
 
 I think you're just wrapping `MogulHandler` into a class.
 Don't hesitate to use the [newtype](https://rust-unofficial.github.io/patterns/patterns/behavioural/newtype.html) idiom

**Comment by taophp** [comment]
Thanks @ptondereau ! Your first suggestion works like a charm ! But... I dont't really understand why. Would you mind to explain ?
I'll dig the newtype idiom.

And thanks again !
