### ISSUE TITLE
Implement static method ?

### ISSUE THREAD

**Issue by taophp** [davidcole1340/ext-php-rs#162]
I wonder if and how it is possible to implement static methods on PHP object from a Rus struct.
Please consider this Rust code:
``` rust
#[php_class]
pub struct MogulHl(MogulHandler);

[php_impl]
impl MogulHl {
    pub fn serialize(&self) -> String {
        serde_json::to_string(&self.0).unwrap().to_string()
    }

    pub fn merge(original:  &MogulHl, challenger: &MogulHl) -> MogulHl {
        MogulHl(mogul_merge(&original.0, &challenger.0))
    }
}
```
I snip out the code out of the scope of my question. If you mind read the whole stuff, a experimental binding to an experimental lib, please have a look to [this repo](https://github.com/taophp/mogul-php/tree/f08a379bcf8193a9967cf356adf1aac0ba4b4170/src).

In this case, I have no problem to use the dynamic method `serialize` on a concrete `MogulHl` object:
```php
$myMogulHl->serialize(); // works like a charm
```
but when I try to call the static (I expect a static PHP method, as I did not use `&self` in the function signature), I got an error:
```php
MogulHl::allow_merge($original,$challengerNotSame); // MogulHl::allow_merge($original,$challengerNotSame)
```

Any idea ? clue ?

**Comment by davidcole1340** [comment]
This should work fine. See this code here which works for me:
```rs
#![cfg_attr(windows, feature(abi_vectorcall))]
use ext_php_rs::prelude::*;

#[php_class]
pub struct TestStatic {
    a: i32,
}

#[php_impl]
impl TestStatic {
    pub fn __construct(a: i32) -> Self {
        Self { a }
    }

    pub fn test(a: &TestStatic, b: &TestStatic) -> String {
        format!("{} {}", a.a, b.a)
    }
}

#[php_module]
pub fn get_module(module: ModuleBuilder) -> ModuleBuilder {
    module
}
```

And running it from PHP:

```php
>>> $x = new TestStatic(5)
=> TestStatic {#2666}
>>> $y = new TestStatic(10)
=> TestStatic {#2665}
>>> TestStatic::test($x, $y)
=> "5 10"
```

- Are you sure you added the `#` prefix to the `[php_impl]` tag?
- Are you sure you recompiled after adding the static method?

**Comment by taophp** [comment]
Many thanks for your answer. Working from it, I finally find the problem: snake_case to camelCase conversion. I've read about it [here in the guide](https://davidcole1340.github.io/ext-php-rs/macros/impl.html#methods), but I did not have it in mind when writing my code. So now,
```php
MogulHl::allowMerge($original,$challengerNotSame); // MogulHl::allow_merge($original,$challengerNotSame);
```
works as expected.

For those who may encounter the same problem, consider using `get_class_methods()` to ensure the way your Rust functions are named in PHP.
