### ISSUE TITLE
implementing Interfaces

### ISSUE THREAD

**Issue by nikeee** [davidcole1340/ext-php-rs#163]
The docs state:
> `#[implements(ce)]` - Implements the given interface on the class. Can be used multiple times. ce must be a valid Rust expression when it is called inside the `#[php_module]` function.

How do I use this to implement an interface provided by the standard library of PHP? For example, I want to implement [`ArrayAccess`](https://www.php.net/manual/en/class.arrayaccess.php) on my own class.

My current approach is this:
```rs
#[php_class]
#[implements(ext_php_rs::zend::class::ClassEntry::try_find("ArrayAccess").unwrap())]
pub struct Test {
}
```
But the `class` type seems to be private:
```
error[E0603]: module `class` is private
   --> src/lib.rs:205:1
```

If I get this to work, how do I actually implement the methods? Does having the appropriate method names suffice (putting renaming of methods aside)?

If this has a solution, I'd love to contribute this to the docs. I really like this library!

**Comment by davidcole1340** [comment]
I don't think I have actually tried to implement an interface, so I will give it a go and report back. To answer your question regarding `ClassEntry`, it is re-exported via `ext_php_rs::zend::ClassEntry::try_find` (https://docs.rs/ext-php-rs/0.7.4/ext_php_rs/zend/type.ClassEntry.html).

**Comment by nikeee** [comment]
I tried adding am example in #167. Do the docs fail due to the version with the interface class entries not being released?
