### ISSUE TITLE
API docs not available for versions 0.8 and 0.8.1

### ISSUE THREAD

**Issue by ju1ius** [davidcole1340/ext-php-rs#175]
See https://docs.rs/crate/ext-php-rs/latest

[Apparently](https://docs.rs/crate/ext-php-rs/0.8.1/builds/647339) there's a PHP version mismatch in the CI configuration.

```
[INFO] [stderr] Error: The current version of PHP is not supported. Current PHP API version: 20190902, requires a version between 20200930 and 20210902
```

**Comment by ptondereau** [comment]
Good catch, I'll take look

**Comment by davidcole1340** [comment]
Version 0.8.2 docs are now building -- https://docs.rs/ext-php-rs/0.8.2/ext_php_rs/
