### ISSUE TITLE
Calling arbitrary PHP class object methods

### ISSUE THREAD

**Issue by AshleySchaeffer** [davidcole1340/ext-php-rs#193]
Figured I'd raise a separate issue for clarity (see #192 ).

Is it possible to call methods on arbitrary PHP class objects, and if so how? I can't find any examples or docs pertaining to this but I could be missing something.

Essentially, I'd like to be able to take a `ZendObject` as a function parameter and call it's methods to retrieve output. I'm wondering if I need to define a replica `php_class` decorated struct, that would wrap the object ~~and then leverage something like the [call_user_func](https://docs.rs/ext-php-rs/latest/ext_php_rs/macro.call_user_func.html#) macro to call it's the methods. I'm unsure how to then approach marshalling the data returned from the object methods (which mostly strings in my case)~~.

I'm really not sure how to approach this if it's possible. Any guidance would be greatly appreciated.

**Comment by ju1ius** [comment]
At the moment the only "ergonomic" way is to either use the [call_user_func!](https://docs.rs/ext-php-rs/latest/ext_php_rs/macro.call_user_func.html) macro, or the [Zval::try_call()](https://docs.rs/ext-php-rs/latest/ext_php_rs/types/type.Zval.html#method.try_call) method.

I you have a reference to a ZendObject that would look like this (give or take)
```rust
let obj: &ZendObject = ...;
let callable = Zval::new();
callable.set_array(vec![obj, "methodToCall"]);
let arguments = vec![];
if let Ok(result) = zv.try_call(arguments) {
    ...
}
```

**Comment by AshleySchaeffer** [comment]
Yeah I think that's more trouble than it's worth for my use case. Thanks for the example, just tried it and it seems to be working as expected.

**Comment by videni** [comment]
@ju1ius  @AshleySchaeffer 

where is the zv variable from please?  

I tried this 
```
        let obj: &ZendObject = ...;

        let callable = Zval::new();
        callable.set_array(vec![o, "hello"]);  // this line won't work, because  the method "hello" is type &str, not ZendObject, I don't know why the example works.

        let arguments = vec![];
        if let Ok(result) = callable.try_call(arguments) {
          dbg!(result);
        }
```

**Comment by ju1ius** [comment]
> callable.set_array(vec![o, "hello"]);

Yes, this obviously doesn't work because you can't make a `Vec` from different types.

So either:
```rust
callable.set_array(vec![o.into_zval(false)?, "hello".into_zval(false)?]);
```
Or, avoiding the temporary Vec allocation:
```rust
let mut array = ZendHashTable::with_capacity(2);
array.push(my_object)?;
array.push("hello")?;
let result = array.into_zval(false)?.try_call(arguments)?;
```
