### ISSUE TITLE
Module Shutdown Function

### ISSUE THREAD

**Issue by AshleySchaeffer** [davidcole1340/ext-php-rs#204]
I can see references to setting a module shutdown function in the `ModuleBuilder`, but I can't figure out what the method needs in the my `get_module` declaration. Is there any guidance on this? 

Sort of feel like a `php_shutdown` macro should exist as a counterpart to the `php_startup` macro.

**Comment by ju1ius** [comment]
@AshleySchaeffer  You're looking for the [ModuleBuilder::shutdown_function()](https://docs.rs/ext-php-rs/latest/ext_php_rs/builders/struct.ModuleBuilder.html#method.shutdown_function) method.

**Comment by AshleySchaeffer** [comment]
Thank you very much
