### ISSUE TITLE
Crate is rebuilt on every build due to rerun-if-env-changed

### ISSUE THREAD

**Issue by joehoyle** [davidcole1340/ext-php-rs#220]
As mentioned in https://github.com/davidcole1340/ext-php-rs/pull/210#issuecomment-1406892456, every time I run `cargo check` etc then the ext-php-rs build script is run, due to the use of `rerun-if-env-changed`.

I tracked it down specifically to the `PATH` env var -- `PHP` and `PHP_CONFIG` don't cause issues (though those env vars are not set). My `$PATH` _is_ stable, so it's not like it's changing. (unless the build script it's self is setting something).

**Comment by rmccue** [comment]
Ran through debugging this with @joehoyle, this actually turns out to be due to:
https://github.com/davidcole1340/ext-php-rs/blob/e6afecbddd8fc9dbf0ef243211fb82ac8864c500/build.rs#L240

When this crate is loaded as a dependency, there's no local `Cargo.lock` (as it's in the root crate instead); this causes it to rebuild every time due to https://github.com/rust-lang/cargo/issues/6003

**Comment by ptondereau** [comment]
> Ran through debugging this with @joehoyle, this actually turns out to be due to:
> 
> https://github.com/davidcole1340/ext-php-rs/blob/e6afecbddd8fc9dbf0ef243211fb82ac8864c500/build.rs#L240
> 
> When this crate is loaded as a dependency, there's no local `Cargo.lock` (as it's in the root crate instead); this causes it to rebuild every time due to [rust-lang/cargo#6003](https://github.com/rust-lang/cargo/issues/6003)

I've introduced that cargo flag recently, but I forgot to remove it. If you have the time, feel free to submit a PR to remove it! I'll be glad to merge it quickly. Thank you for this investigation

**Comment by rmccue** [comment]
Should we retain it behind a flag? Might be useful for debugging/development purposes.

**Comment by ptondereau** [comment]
> Should we retain it behind a flag? Might be useful for debugging/development purposes.

Let just remove it for the moment and see later if we can provide a better solution
