### ISSUE TITLE
Database driver usecase

### ISSUE THREAD

**Issue by khaf** [davidcole1340/ext-php-rs#244]
We have a database driver that we are trying to write a PHP equivalent for. Is it supported in this library? We need to keep that driver in memory for it to work (connection pools and some other stuff that need to stay alive in the process memory) and I'm under the impression that that is possible in PHP, but is it supported in this library?

If so, can anyone point us in the right direction?

**Comment by khaf** [comment]
For future readers, you don't need to do anything special. even php-fpm follows a process-based model, so you just need to have a global instance in your driver code. If you want a shared instance between all your PHP processes, you either use shared memory, or use some kind of IPC.

**Comment by danog** [comment]
For reference, I've started work on an async mongodb driver based on ext-php-rs and php-tokio here: https://github.com/nicelocal/mongo-php-async-driver/
