### ISSUE TITLE
Performance: There seems to be a runtime related overhead with using ext-php-rs extensions in PHP

### ISSUE THREAD

**Issue by bgrande** [davidcole1340/ext-php-rs#303]
First of all: Thank you for the great work! It's very interesting and promising. 

While testing a simple extension's runtime (measuring time in php script) and running the script multiple times I noticed a constant overhead of around >400ms (at my system) related to my extension build with ext-php-rs. 
The comparison for the overhead is a comparable native PHP function and a pure Rust version of it. 

Here are the basics:

__Rust ext-php-rs__
```Rust
use ext_php_rs::prelude::*;

#[php_function]
pub fn find_mapping(needle: String, haystack: Vec<String>) -> Option<String> {
    match haystack.iter().position(|elem| elem == &needle) {
        None => None,
        Some(_ind) => Some(needle)
    }
}

#[php_module]
pub fn module(module: ModuleBuilder) -> ModuleBuilder {
    module
}
```

This got built via `cargo build --release`.

__Rust pure__
```Rust
fn find(needle: String, haystack: &Vec<String>) -> Option<String> {
    match haystack.iter().position(|elem| elem == &needle) {
        None => None,
        Some(_ind) => Some(needle)
    }
}
````

Also built with `cargo build --release`.

__PHP with ext-php-rs__
```PHP
function find(string $testString, array $randomStrings): string {
  return find_mapping($testString, $randomStrings);
}
```
using sth. like `/usr/bin/php -d extension=./target/release/librs_php_ext2.so test.php`

__PHP native__
```PHP
function find(string $testString, array $randomStrings): string {
  if ($index = array_search($testString, $randomStrings)) {
    return $testString;
  }
  return '';
}
```

`$randomStrings` looks like this:
```PHP
$randomStrings = [];
for ($i = 0; $i < 9999999; $i++) {
    $randomStrings[] = hash('sha1', random_bytes(5));
}
```

Now, measuring the times with `$start = microtime(true);` and `$end = microtime(true)` in the script gives me similar results (depending on the values' position and my machine, of course) like this (for the same string):
```
time taken with Rust: '413.46788406372ms'
time taken with PHP internal: '8.3808898925781ms'
```

While Rust pure is quite what you'd expect:
```
Time elapsed in find() is: 4.85131ms
```

Are there any known issues or did anybody have a similar experience?

**Comment by bartvanhoutte** [comment]
Having similar experience, it seems like converting data from PHP to rust and vice versa is the culprit?

**Comment by bgrande** [comment]
@bartvanhoutte I'm not entirely sure. I haven't had time to dig through the whole library code so far. 
But yes, either it's related to data conversion or some C binding mapping.

**Comment by danog** [comment]
Yeah data conversion is not the direct culprit here, as no conversion is being done here, most of the library just wraps PHP's zend datastructures.
I've encountered similar performance issues and I'm planning to debug them once I have some more time...

**Comment by bgrande** [comment]
Thank you @danog!

I just tried running the performance test with gradually increasing the size of the array with random data. 
The smaller the array the closer Rust's and PHP native's performance are. The bigger the array, the longer the Rust extension takes. 

Therefore, my conclusion: It might be related to the memory usage somehow.

**Comment by bartvanhoutte** [comment]
Thanks @danog.

@bgrande I've noticed similar behavior when writing a function and increasing the amount of arguments passed on to the function.

**Comment by bgrande** [comment]
@bartvanhoutte that's interesting. Might also be memory related.

**Comment by ju1ius** [comment]
@bgrande  Conversion between PHP and Rust types is not free. The structures have to be allocated and the bytes copied.

Try accepting Zend types instead and you should get comparable performance:

```rs
#[php_function]
pub fn find_mapping(needle: &ZendStr, haystack: &ZendHashTable) -> Option<&ZendStr> {
    todo!()
}
```

**Comment by bgrande** [comment]
Ok, finally an update here:
I tested this with some minimal versions and the culprit definitely is the haystack parameter. Which makes sense because this is the data intense part with a huge array of strings. 

However I tested @ju1ius suggestions and saw some real improvements here:
```rust
#[php_function]
pub fn find_mapping(needle: &Zval, haystack: &ZendHashTable) -> Option<String> {
    match haystack.iter().position(|elem| elem.1.str() == needle.str()) {
        None => None,
        Some(_ind) => needle.string()
    }
}
```

With that I'm down to avg for a bit more than double the native PHP version. Which is way less than before but still a relatively huge difference. 

It might work even better with a reference return value but that didn't work for me due to having to define lifetime specifiers. Which the `php_function` doesn't seem to support right now.

**Comment by ju1ius** [comment]
> It might work even better with a Zval reference return value but that didn't work for me due to having to define lifetime specifiers. Which the `php_function` macro doesn't seem to support right now.

Returning references from Rust functions «exported» to PHP cannot be supported. The Zend Engine is a C API and thus cannot «understand» with Rust's generics and lifetimes.

Even if it were supported, it would be the wrong thing to do in your case. Whenever you return a reference-counted value from a PHP function, you must increment it's reference count. If your function were implemented in C, it would return a copy of the `zval needle` after incrementing the reference count of the underlying `zend_string`, using the [`RETURN_COPY(needle)`](https://heap.space/search?project=php-src&defs=RETURN_COPY) macro.

Also, remember that Zend Strings are just bytes without an encoding. They're conceptually equivalent to a `Box<[u8]>` for persistent strings, or to an `Rc<[u8]>` for non-persistent strings. So going back-and-forth between `ZendString` and `String` requires not only copying the bytes, but also _potentially_ performing UTF-8 validation.

So a more performant implementation should look like this:
```rust
#[php_function]
pub fn find_mapping(needle: &Zval, haystack: &ZendHashTable) -> Option<ZVal> {
    haystack.iter().find_map(|(_, value)| if value.zend_str() == needle.zend_str() {
        Some(value.shallow_clone())
    } else {
        None
    })
}
```
