### ISSUE TITLE
zend_fetch_function_str causes a memory access error on Windows

### ISSUE THREAD

**Issue by EdmondDantes** [davidcole1340/ext-php-rs#348]
Problem essence:

Attempting to get a pointer to a PHP function via `Function.try_from_function` results in accessing a non-existent memory area.
The operation is attempted within the php_startup function.
Platform: Windows 11/ZTS PHP 8.3.4.

```rust
#[php_startup]
pub fn startup() {
    println!("PHP extension started");
    unsafe {
        zend_fetch_function_str("\0".as_ptr() as *const i8, 1); <-- MEMORY ***
    }
}
```

I haven’t had time to fully investigate the issue yet, but using a debugger, I managed to determine the low-level cause. The zend_fetch_function_str function uses EG() to access the function table. However, for some reason, it calculates the pointer incorrectly. The memory address where the pointer to EG should reside contains 0. Naturally, nothing works.

I suspect that:

This function cannot be called at this stage.
There’s a nuance related to ZTS.
I cannot prove either yet. Perhaps one of you, friends, knows the answer. But I will definitely share the results of my investigation.

**Comment by Xenira** [comment]
Thanks for the report.
I know that stuff is not available during startup. See https://github.com/davidcole1340/ext-php-rs/issues/326#issuecomment-2418014295

Let me know if you find out more.

**Comment by EdmondDantes** [comment]
Update.

```c
PHP_MINIT_FUNCTION(test)
{
	// If the ZEND_TSRMLS_CACHE_UPDATE() is in RINIT, move it
	// to MINIT to ensure access to the compiler globals
#if defined(COMPILE_DL_MY_EXTENSION) && defined(ZTS)
	ZEND_TSRMLS_CACHE_UPDATE();
#endif

	zend_function* original;

	//original = zend_hash_str_find_ptr(CG(function_table), "var_dump", sizeof("var_dump") - 1);
	original = zend_fetch_function_str(ZEND_STRL("var_dump"));

	if (original != NULL) {
		original_handler_var_dump = original->internal_function.handler;
		original->internal_function.handler = my_overwrite_var_dump;
	}

	return SUCCESS;
}
```

My very first idea was to test a similar situation but implemented strictly according to the rules in pure C with the same PHP in the same environment.
It turned out that the `zend_fetch_function_str` function call works just as well as `zend_hash_str_find_ptr(CG(function_table), "var_dump", sizeof("var_dump") - 1);`.

I also tested the hypothesis regarding the influence of ZTS, but it was not confirmed either.

**Comment by EdmondDantes** [comment]
Update2

So, the program crashes due to the value of gs:[58h] (TLS), which, during a call from Rust, differs from the same call made from another DLL. Unfortunately, the reasons remain unclear :(

**Comment by EdmondDantes** [comment]
@Xenira 

I haven't laughed this hard in a long time.

I had to go through almost the entire PHP core code during the loading phase to figure out that, on the one hand, it was my mistake, and on the other hand, a lack of documentation.

The issue was that I accidentally swapped the MINIT function with SHUTDOWN in my C test file. As a result, the C DLL managed to initialize correctly, but the Rust DLL wreaked havoc :)

The outcome: you cannot access the EG structure in the MINIT function. According to the core code, only CG can be accessed at that stage. It was proved!

This needs to be added to the documentation!

**Comment by Xenira** [comment]
@EdmondDantes thank you for digging so deep into this. Glad you found the cause.
