### ISSUE TITLE
how support php7.*?

### ISSUE THREAD

**Issue by shanliu** [davidcole1340/ext-php-rs#46]

**Comment by willbrowningme** [comment]
The repository readme states:

> This project only works for PHP >= 8.0 (for now). Due to the fact that the PHP extension system relies heavily on C macros (which cannot be exported to Rust easily), structs have to be hard coded in.

**Comment by davidcole1340** [comment]
Yeah PHP 7.4 is not on my roadmap since active support ends at the end of this year. PHP 8.1 has a higher priority - I believe it already works (not tested). But who knows, maybe one day I will give it a go, but there are more important things to do first.
