### ISSUE TITLE
Auto-generate stubs for IDE auto-completion ?

### ISSUE THREAD

**Issue by Lctrs** [davidcole1340/ext-php-rs#61]
Don't know how hard it would be to implement, but it would be nice if this project could auto-generate stubs for the extension on build to be used for auto-completion in an IDE.

**Comment by davidcole1340** [comment]
I'm not sure how it would generate a stub file from Rust without a CLI application, and at that point it would probably be easier to use `ReflectionExtension` in a PHP script for that. Have you had a look at this: https://github.com/sasezaki/php-extension-stub-generator

**Comment by Lctrs** [comment]
Okay, I was not very satisfied with various projects I found online related to this subject. They were either outdated and/or not feature complete.

So I went on and implemented mine : https://github.com/Lctrs/php-ext-stubs-generator
