### ISSUE TITLE
Add `FromZval` derive macro

### ISSUE THREAD

**Issue by davidcole1340** [davidcole1340/ext-php-rs#75]
Ability to derive `FromZval` (and potentially `IntoZval`) using a derive macro. Could be used in two situations:

- Enums.  Data type would be mixed, and would act as a mixed type parameter. Example:
```rust
#[derive(FromZval)]
pub enum IntOrBool {
    Integer(u32),
    Boolean(bool),
}

// translates to

impl FromZval<'_> for IntOrBool {
    const TYPE: DataType = DataType::Mixed;
    fn from_zval(zval: &'_ Zval) -> Option<Self> {
        if let Some(integer) = u32::from_zval(zval) {
            Some(integer)
        } else if let Some(boolean) = bool::from_zval(zval) {
            Some(boolean)
        } else {
            None
        }
    }
}
```

- Structs. Data type would be object, and the struct fields would be read from the objects properties. Primarily for passing `stdClass` into Rust. Example:

```rust
#[derive(FromZval)]
pub struct ExampleStdClass {
    a: i32,
    b: String,
    c: bool,
}

// translates to

impl FromZval<'_> for ExampleStdClass {
    const TYPE: DataType = DataType::Object(None);

    fn from_zval(zval: &'_ Zval) -> Option<Self> {
        let obj = zval.object()?;

        Some(Self {
            a: obj.get_property("a").ok()?,
            b: obj.get_property("b").ok()?,
            c: obj.get_property("c").ok()?,
        })
    }
}
```

**Comment by vodik** [comment]
I like it. It should be paired with a `IntoZval` as well.

Something worth keeping an eye on is [PHP 8.1 enums](https://stitcher.io/blog/php-enums). I don't think this should conflict through: a reasonable approach is probably to either add a new `#[php_enum]` attribute (or make `php_class` smarter - idk how its implemented under the hood) and make sure that its mutually exclusive from these derive macros.
